version: '3.1'

services:
  api:
    image: emt-api
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=${EMT_DATABASE_URL}
    ports:
      - '3004:3000'

  ui:
    image: emt-client
    environment:
      - PORT=80
      - API_URL=http://api:3000
      - RAILS_ENV=production
    ports:
      - '80:80'
    depends_on:
      - api
