version: '3.1'

services:
  api:
    image: emt-api
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_URL=${EMT_DATABASE_URL}
      - SECRET_KEY_BASE=${EMT_SECRET_KEY_BASE}
    ports:
      - '3004:3000'

  ui:
    image: emt-client
    environment:
      - PORT=80
      - NODE_ENV=production
    ports:
      - '80:80'
    depends_on:
      - api
