version: '3.1'

services:
  api:
    image: emt-api
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=${EMT_DATABASE_URL}
      - SECRET_KEY_BASE=${EMT_SECRET_KEY_BASE}
    ports:
      - '3004:3000'

  ui:
    image: emt-client
    environment:
      - PORT=80
      - API_URL=http://redpola-emt.southeastasia.cloudapp.azure.com:3004
      - NODE_ENV=staging
    ports:
      - '80:80'
    depends_on:
      - api
