AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb
    - public/**/*
    - app/assets/**/*
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantBegin:
  Description: "Don't use begin blocks when they are not needed."
  StyleGuide: '#begin-implicit'
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false


Style/MutableConstant:
  Description: 'Do not assign mutable objects to constants.'
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  StyleGuide: '#percent-w'
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: key
  SupportedHashRocketStyles:
    - key
    - table
  EnforcedColonStyle: key
  SupportedColonStyles:
    - key
    - table

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Metrics/AbcSize:
  Max: 35
