mutation loginUser($input: LoginInput!) {
  loginUser(input: $input) {
    token
  }
}

mutation createUser($input: CreateUserInput!) {
  createUser(input: $input) {
    createdUser {
      id
      username
      email
      createdAt
    }
  }
}

mutation updateUserInfo($input: UpdateUserInput!) {
  updateUser(input: $input) {
    updatedUser {
      id
      username
      email
    }
  }
}

mutation updatePassword($input: UpdatePasswordInput!) {
  updatePassword(input: $input) {
    passwordIsUpdated
  }
}

mutation createProject($input: CreateProjectInput!) {
  createProject(input: $input) {
    createdProject {
      id
      name
      description
    }
  }
}

mutation updateMemberRoleInProject($input: UpdateMemberRoleInProjectInput!) {
  updateMemberRoleInProject(input: $input) {
    updated
  }
}
