query getCurrentUser {
  currentUser {
    id
    username
    role
    avatar
  }
}

query getCurrentUserProfile {
  profile: currentUser {
    id
    username
    email
    role
    avatar
  }
}

query getCurrentUserOnClient {
  currentUser @client {
    id
    username
    role
    avatar
  }
}

query getAllUsers {
  users {
    avatar
    id
    username
    email
    createdAt
  }
}

query getProjectOfCurrentUser {
  projectsAsMemberOfCurrentUser {
    id
    name
    description
  }
  projectsAsAdminOfCurrentUser {
    id
    name
    description
  }
}

query getMembersByProjectId($projectId: ID!) {
  projectMembers(projectId: $projectId) {
    id
    role
    user {
      id
      email
      username
      role
      avatar
    }
  }
}

query getProjectById($id: ID!) {
  project(id: $id) {
    id
    name
    description
    isManagedByCurrentUser
  }
}
