query getCurrentUser {
  currentUser {
    id
    username
    role
  }
}

query getAllUsers {
  users {
    id
    username
    email
    createdAt
  }
}

query getProjectOfCurrentUser {
  projectsAsMemberOfCurrentUser {
    id
    name
    description
  }
  projectsAsAdminOfCurrentUser {
    id
    name
    description
  }
}

query getMembersByProjectId($projectId: ID!) {
  projectMembers(projectId: $projectId) {
    id
    role
    user {
      id
      email
      username
      role
    }
  }
}

query getProjectById($id: ID!) {
  project(id: $id) {
    name
    description
  }
}
