mutation createService($input: CreateServiceInput!) {
  createService(input: $input) {
    createdService {
      id
      name
      description
      createdAt
    }
  }
}

mutation updateService($input: UpdateServiceInput!) {
  updateService(input: $input) {
    updatedService {
      id
      name
      description
      createdAt
    }
  }
}