query getCompanyDetails($companyId: ID!, $memberAmount: Int!){
    company(companyId: $companyId){
        id
        status
        name
        description
        email
        address
        phoneNumber
        plan {
            id
            name
        }
        companyMemberCount
        companyMembers(first: $memberAmount) {
            id
            roles
            user {
                id
                username
                avatar
            }
        }
    }
}
